export const MEMORY_KINDS = [
  "product",
  "hs_code",
  "naics",
  "material",
  "process",
  "waste",
  "distribution_state",
  "label_claim",
  "export_classification",
  "product_flag",
  "kbli",
  "market",
  "location",
  "license",
  "sni",
  "tax",
  "contact",
  "operational",
  "preference",
  "other",
] as const;
